spring:
  application:
    name: user_center
# DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/szk?useSSL=false&serverTimezone=UTC
    username: root
    password: Aa@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
server:
  port: 8080
  servlet:
    context-path: /api
